src/Authorizer.ts
src/__test__/index.test.ts
src/__test__/server.ts

Hide the casbin nature in request to server endpoint

---

src/Cache.ts
src/__test__/index.test.ts

small performance enhanced

---

package.json
yarn.lock

fix: fix dependency miss

---

package.json
yarn.lock

fix: #28 
same as: https://github.com/casbin/casbin.js/pull/29

fix: fix dependency conflict with react

---

.github/semantic.yml
.github/workflows/ci.yml

I have test lint and tests, and it works out.
But I truly have no idea how to test release. Please review this carefully.

feat: add support for GitHub Actions

---

README.md

docs: change build badge

---

package.json
yarn.lock

build: add npm-run-all as dev dependency

---

package.json

ci: fix ci build

---

src/Authorizer.ts

feat: add custom header option

---

README.md

docs: fix setUser usage

---

src/Authorizer.ts

fix: won't reparse the response

---

src/Authorizer.ts

Reverts casbin/casbin.js#59
I misunderstood the processing flow, there's no reason to do this.
ref to my comments in https://github.com/casbin/casbin.js/issues/58

revert: Revert "fix: won't reparse the response"

---

src/Cache.ts

Fix: https://github.com/casbin/casbin.js/issues/72
in ssr cases window is not defined and localstorage not available

fix: avoid errors in case of ssr

---

.github/dependabot.yml

fix: depenabot pull request meesage prefix

---

src/Authorizer.ts
src/__test__/enforcer.test.ts
src/__test__/models.ts

feat: support domain at auto mode

---

src/index.ts
src/syncedEnforcer.ts

Revert "refactor: remove syncdEnforcer"

---

examples/in_operator_model.conf
src/coreEnforcer.ts
src/model/functionMap.ts
src/util/builtinOperators.ts
src/util/util.ts
test/enforcer.test.ts
test/model.test.ts
test/util.test.ts

ref to: https://github.com/casbin/node-casbin/compare/v5.10.0...v5.11.4
about: https://github.com/casbin/node-casbin/issues/317
prepare for prepublish

feat: sync with upstream

---

package.json
src/util/util.ts
test/util.test.ts

This helps to reduce the volume

feat: implement csv parser

---

src/enforcer.ts
src/persist/defaultFilteredAdapter.ts
src/persist/index.ts
src/persist/memoryAdapter.ts
test/enforcer.test.ts
test/utils.ts

Signed-off-by: Zixuan Liu <nodeces@gmail.com>
- Remove unnecessary method from MemoryAdapter
- Support new MemoryAdapter by array

fix: rename StringAdapter to MemoryAdapter

---

src/cachedEnforcer.ts
src/config.ts
src/coreEnforcer.ts
src/enforcer.ts
src/model/model.ts
src/syncedEnforcer.ts
test/enforcer.test.ts

refactor: Remove file-related comments and arguments

---

.releaserc.json

Signed-off-by: Zixuan Liu <nodeces@gmail.com>

ci: config release branches for semantic-release

---

.github/workflows/main.yml

Signed-off-by: Zixuan Liu <nodeces@gmail.com>

ci: remove v1 branch limit

---

CHANGELOG.md
README.md
package.json

Signed-off-by: Zixuan Liu <nodeces@gmail.com>

fix: update doc and release channel

---

.github/workflows/ci.yml

Fix: ![image](https://user-images.githubusercontent.com/41513919/216643040-bd0ac24b-8869-4df0-9beb-468a84cd3b47.png)

fix: set Node version 18 in semantic-release
